
volumes:
  pg_data:
  static:
  media:
  frontend:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: s418963/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media

  frontend:
    image: s418963/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend/
    volumes:
      - frontend:/frontend

  gateway:
    image: s418963/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
      - frontend
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
      - frontend:/frontend  